version: "3"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  web:
    build: .
    command: bash -lc "yarn install && yarn storybook"
    hostname: editor-dev
    tty: true
    stdin_open: true
    volumes:
      - .:/editor:delegated
    ports:
      - "6006:6006"
    environment:
      - STORYBOOK_SIGNAL_URL=ws://localhost:6006/ws/signal
      - STORYBOOK_PROVIDER_URL=ws://localhost:6006/ws/provider
    depends_on:
      - "signal"
  signal:
    build: .
    command: bash -lc "yarn service dev"
    volumes:
      - .:/editor:delegated
    ports:
      - "6001:6001"
    environment:
      - PORT=6001
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - "db"
      
