version: "3"
services:
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  web:
    build: .
    command: bash -lc "yarn install && yarn storybook"
    hostname: editor-dev
    tty: true
    stdin_open: true
    volumes:
      - .:/editor:delegated
    ports:
      - "6006:6006"
