version: "3"
services:
  gateway:
    image: nginx
    volumes:
      - ./terraform/nginx-dev:/etc/nginx/templates
    depends_on:
      - "web"
      - "signal"
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - STATIC_URL=http://web:3000
      - WEBSOCKET_URL=http://signal:6001
      - API_URL=http://signal:6001
  db:
    environment:
      - POSTGRES_PASSWORD=password
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - "./volumes/postgres:/var/lib/postgresql/data"
  web:
    build: .
    command: bash -lc "yarn client dev"
    hostname: editor-dev
    tty: true
    stdin_open: true
    volumes:
      - .:/editor:delegated
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SIGNAL_URL=ws://localhost:8080/ws/signal
      - NEXT_PUBLIC_PROVIDER_URL=ws://localhost:8080/ws/provider
    depends_on:
      - "signal"
  signal:
    build: .
    command: bash -lc "yarn service dev"
    volumes:
      - .:/editor:delegated
    ports:
      - "6001:6001"
    environment:
      - PORT=6001
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    depends_on:
      - "db"
      
