name: PR checks

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        - image: node:14.x
          env:
            PG_HOST: localhost
            PG_USER: ubuntu
        - image: postgres:13
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: password
              POSTGRES_DB: postgres
            ports:
              5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - checkout
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn
    - run: yarn format:check
    - run: ping postgres
    - run: yarn service test
      env:
        DATABASE_URL: postgres://postgres:password@localhost:5432/postgres?sslmode=disable
    - run: yarn build
