# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - uses: actions-hub/gcloud@master
      env:
        PROJECT_ID: willdocs
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: info
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Init Terraform
      run: |
        terraform -chdir=terraform init
        export WEB_BUCKET=$(terraform -chdir=terraform/ output -raw static-bucket)
        export SERVICE_BUCKET=$(terraform -chdir=terraform/ output -raw private-bucket)
    - run: yarn
    - run: |
        # Build client bundle
        BASE_SERVICE_URL=$(terraform -chdir=terraform/ output -raw dns_name)
        export NEXT_PUBLIC_SIGNAL_URL="ws://$BASE_SERVICE_URL/ws/signal"
        export NEXT_PUBLIC_PROVIDER_URL="ws://$BASE_SERVICE_URL/ws/provider"
        yarn client build
        STATIC_BUCKET=$(terraform -chdir=terraform/ output -raw static-bucket)
        gsutil cp -r ./packages/client/out gs://$STATIC_BUCKET/client
    - run: yarn service build
    - run: |
        # zip up service bundle
        tar cfz service.tgz packages/service/dist/* packages/service/db/migrations
        PRIVATE_BUCKET=$(terraform -chdir=terraform/ output -raw private-bucket)
        gsutil cp service.tgx gs://$PRIVATE_BUCKET/service
    - name: Terraform Deploy
      run: |
        terraform -chdir=terraform taint google_compute_instance.app
        terraform -chdir=terraform apply --auto-approve
