# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Init Terraform
      run: |
        terraform -chdir=terraform init
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - run: yarn
    - run: |
        BASE_SERVICE_URL=$(terraform -chdir=terraform/ output --json | jq -r '.dns_name.value')
        export NEXT_PUBLIC_SIGNAL_URL="ws://$BASE_SERVICE_URL/ws/signal"
        export NEXT_PUBLIC_PROVIDER_URL="ws://$BASE_SERVICE_URL/ws/provider"
        yarn client build
    - run: yarn service build
    - run: |
        # zip up service bundle
        tar cfz service.tgz packages/service/dist/* packages/service/db/migrations
    - id: upload-service-zip
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        path: ./service.tgz
        destination: willdocs/service
    - id: upload-client-bundle
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        path: ./packages/client/out
        destination: willdocs-2/client
        parent: false
    - name: Terraform Deploy
      run: |
        terraform -chdir=terraform taint google_compute_instance.app
        terraform -chdir=terraform apply --auto-approve
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
