# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: yarn
    - run: yarn client build
      env: 
        BASE_URL: "bingobongo.ml"
        STORYBOOK_SIGNAL_URL: "ws://${BASE_URL}/ws/signal"
        STORYBOOK_PROVIDER_URL: "ws://${BASE_URL}/ws/provider"
    - run: yarn service build
    - run: |
        # zip up service bundle
        tar cfz service.tgz packages/service/dist/*
    - id: upload-service-zip
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        path: ./service.tgz
        destination: willdocs-1/service
    - id: upload-client-bundle
      uses: google-github-actions/upload-cloud-storage@main
      with:
        credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        path: ./packages/client/dist/webpage
        destination: willdocs-2/client
        parent: false